name: Auto Label Issues

on:
  issues:
    types:
      - opened

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Check issue title and add label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            ${{ contains(github.event.issue.title, 'bug') && 'bug' || '' }}
            ${{ contains(github.event.issue.title, 'feature') && 'enhancement' || '' }}
