name: Test Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            build_command: build:win
          - os: macos-latest
            build_command: build:mac

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install

      - name: Run build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run ${{ matrix.build_command }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: testbuild-${{ matrix.os }}-${{ github.run_id }}
          path: ${{ matrix.os == 'windows-latest' && 'dist/*.exe' || 'dist/*.dmg' }}
